### ISSUE TITLE
Create bin that calls the phar

### ISSUE THREAD

**Issue by fprochazka** [phpstan/phpstan-shim#1]
Providing the `.phar` as composer bin directly is bad, because the phar appears in project two times and PhpStorm is confused from it, and claims duplicated classes.

There should be a `phpstan` binary (that actually calls the phar), that can be safely symlinked.

**Comment by TomasVotruba** [comment]
How would you differentiate between normal `vendor/bin/phpstan` and this one if they'd share a name?

**Comment by ondrejmirtes** [comment]
Solved in 0.9.1 thanks to @JanTvrdik #10 .
