### ISSUE TITLE
PHPstan conf directory

### ISSUE THREAD

**Issue by MartinMystikJonas** [phpstan/phpstan-shim#11]
Could conf directory from phptan/phpstan be part of phpstan/phpstan-shim package? I would like to include these configs when using phpstan/phpstan-shim.

**Comment by ondrejmirtes** [comment]
It is part of the package, otherwise it would not work 😊

You can reference the files like this:

```
includes:
	- phar://phpstan.phar/conf/config.level0.neon
```
