### ISSUE TITLE
On windows: "'bash' is not recognized as an internal or external command,"

### ISSUE THREAD

**Issue by dakorpar** [phpstan/phpstan-shim#13]
Not sure if problem is in this package or phpstan actually but I get error when runing
vendor\bin\phpstan.bat
'bash' is not recognized as an internal or external command,
operable program or batch file.

edit:
works when calling vendor\bin\phpstan.phar.bat, but not really sure why upper isn't... I believe it's still a bug...

**Comment by ondrejmirtes** [comment]
Hi, can you show me how `vendor\bin\phpstan.bat` looks like? It's autogenerated by Composer so I'd first verify that it doesn't output some gibberish.

**Comment by dakorpar** [comment]
```
@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../phpstan/phpstan-shim/phpstan
bash "%BIN_TARGET%" %*

```

**Comment by ondrejmirtes** [comment]
Please try the latest commit, I tried something: https://github.com/phpstan/phpstan-shim/commit/967719067aa04a87a9782b97be739a61127c7537
