### ISSUE TITLE
RootDir phar:// prefix

### ISSUE THREAD

**Issue by pauliusrum** [phpstan/phpstan-shim#14]
Hi,

how to use %rootDir% when running phpstan.phar? When I pass %rootDir% to an extension class i get a path like this: "phar:///home/xxx/yyy/vendor/phpstan/phpstan-shim/phpstan.phar". If I want to pass a directory for example to symfony extension (https://github.com/lookyman/phpstan-symfony#configuration) i can't really do that.

**Comment by lookyman** [comment]
You can just use a path relative to the current working directory and it should work.

**Comment by pauliusrum** [comment]
Yes, but I wanted to avoid using relative paths since one can run code inspection on different envirnoment, in different working directories (local development, CI agents, etc..). But i guess there's no other choice.
