### ISSUE TITLE
bootstrap.php prevents autoloading of certain files from shared dependencies with project

### ISSUE THREAD

**Issue by fmasa** [phpstan/phpstan-shim#32]
Even though this package should make it easier to use side-by-side with application dependencies, there is problem with way Composer autoincludes files autoloaded via `autoload.files`.

The file, that makes problems, is `vendor/nette/di/compatibility.php`.

## What happens
When Composer includes bootstrap.php, it includes files from all dependencies, that are mentioned in `autoload` with type `files`. Composer then saves [file identifiers](https://github.com/composer/composer/blob/a066dd9e00e0b703fdd97ccd6f562e1fd0559e25/src/Composer/Autoload/AutoloadGenerator.php#L916) of those files to `$GLOBALS` (`$GLOBALS['__composer_autoload_files'][$fileIdentifier] = true`) "Same" files used by project are then skipped. *Note that this is may or may not work depending on order of packages calculated by Composer.*

## Cause
This is regression caused by https://github.com/phpstan/phpstan-shim/commit/e7dd0a052367fbefc8e96a968e1cf717fee161ec.

phpstan/phpstan-shim autoloader probably should not pollute application autoloading if it's not running in context of phpstan analysis.

**Comment by ondrejmirtes** [comment]
Hi, I plan to make some changes in this area, I need to have package with PHPStan as PHAR be usable by everyone.

**Comment by fmasa** [comment]
Is there a way for me to help? :slightly_smiling_face: 

There is dirty way to work around this issue in my project (defining `__PHPSTAN_RUNNING__` constant in some custom bootstrap file, that is not analyzed), but it can be rather confusing for other users.

**Comment by ondrejmirtes** [comment]
You can try :) My plan is to have a custom autoloader inside bootstrap.php that only loads `PHPStan` and `PhpParser` classes from inside the PHAR when they are requested.

**Comment by ondrejmirtes** [comment]
Please try current dev-master. https://github.com/phpstan/phpstan-shim/commit/10caff50504e77c038afca185b6a247d13dc560e
