### ISSUE TITLE
Broken sync with packagist

### ISSUE THREAD

**Issue by xificurk** [phpstan/phpstan-shim#4]
Although, version 0.8 is tagged in this repository, there is no such version on packagist:
https://packagist.org/packages/phpstan/phpstan-shim

**Comment by gedimin45** [comment]
Hello! Any way to fix this? :)

**Comment by mhujer** [comment]
I used this in my `composer.json` as a workaround:

```
"phpstan/phpstan-shim": "dev-master#48c8ef92966a0caf7ea55eb48792b44a48c2b576",
```

**Comment by xificurk** [comment]
Packagist seems to be in sync with repo now.
