### ISSUE TITLE
Use PHP-Scoper

### ISSUE THREAD

**Issue by theofidry** [phpstan/phpstan-shim#7]
I see that you are using [phpstan-compiler](https://github.com/fprochazka/phpstan-compiler) to prefix a code. But maybe instead of going for a in-house solution, [PHP-Scoper](https://github.com/humbug/php-scoper) could be used for it? The idea is basically the same, but it tries to do it in a more generic way.

Let me know if you're interested, otherwise feel free to close that issue :)

**Comment by ondrejmirtes** [comment]
Hi,
the prefixing won't soon be needed once we switch to a static reflection solution 😊 So I don't want to invest into changing it now because we will be able to scrap it altogether in like 3 months I guess 😊
