### ISSUE TITLE
0.8.5 release

### ISSUE THREAD

**Issue by madmanmax** [phpstan/phpstan-shim#8]
I was wondering if there will be a new release since [phpstan/phpstan](https://github.com/phpstan/phpstan) is now at [0.8.5](https://github.com/phpstan/phpstan/releases/latest).

**Comment by ondrejmirtes** [comment]
Hi,
let me assure you that for the PHAR version, 0.8.5 wouldn't bring anything new when compared to 0.8.4, it solved a specific issue when installed `phpstan/phpstan` via Composer.

But of course I'd publish PHPStan PHAR 0.8.5, but I encountered a specific build problem. I aim to solve this for 0.9 release which is coming soon. Once 0.9 is out, I will return to publishing PHARs as well.

Thank you for understanding.

**Comment by madmanmax** [comment]
Hi @ondrejmirtes, thanks for the quick reply. Good to know there will be a 0.9 release. I was only asking because there was a small fix in the 0.8.5 version. But it can wait till 0.9. Looking forward to the new release :)

**Comment by ondrejmirtes** [comment]
I was able to solve this (reference: https://github.com/Ocramius/PackageVersions/issues/48) so the 0.8.5 PHAR is published.
