### ISSUE TITLE
Sign phar file in separate file

### ISSUE THREAD

**Issue by eclipxe13** [phpstan/phpstan-shim#9]
Please consider adding a detached signature to the phpstan.phar releases, so the validity of the release phar can also be verified. This would also allow installing phpstan via [phive](https://phar.io/).

**Comment by ondrejmirtes** [comment]
Hi,
I've been looking into https://phar.io and it looks like any installable tool has to be added manually so in order for `phive install phpstan` to work I have to contact the authors. Is that right?

**Comment by eclipxe13** [comment]
Just make a pull request to the list repository. If you are using github
releases and sign the pharmacy you are ready.

**Comment by ondrejmirtes** [comment]
I added the `asc` signature to the [releases over at phpstan/phpstan](https://github.com/phpstan/phpstan/releases/tag/0.8.5) and sent a PR to Phive: https://github.com/phar-io/phar.io/pull/23
